Project/Project/Models/DietVR.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project.Models
{
    public class DietVR
    {
        public int ID { set; get; }
        //Tieu De
        [Required(ErrorMessage = "Dữ liệu chưa được nhập")]
        [StringLength(500, ErrorMessage = "Số lượng ký tự từ 20-500", MinimumLength = 2)]
        public String Title { set; get; }

        //Noi Dung
        [Required(ErrorMessage = "Dữ liệu chưa được nhập")]
        [StringLength(5000, ErrorMessage = "Số lượng ký tự từ 20-5000", MinimumLength = 2)]
        public String Body { set; get; }

        //Ngay dang
        [Required(ErrorMessage = "Dữ liệu chưa được nhập")]
        [DataType(DataType.DateTime)]
        public DateTime DateCreate { set; get; }

        //1 bài viết của 1 người dùng
        public virtual UserProfile UserProfile { set; get; }
        public int UserProfileID { set; get; }
        // 1 bài viết có nhiều Comment
        public virtual ICollection<Comment> Comments { set; get; }
        public virtual ICollection<RatingVR> RatingVRs { set; get; }
        //1 bài viết có nhiều tag
        public virtual ICollection<Tag> Tags { set; get; }
    }
}

Project/Project/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class CommentController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Comment/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.DietVRs).Include(c => c.LapTrinhs);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create

        public ActionResult Create()
        {
            ViewBag.DietVRID = new SelectList(db.DietVRs, "ID", "Title");
            ViewBag.LapTrinhID = new SelectList(db.Laptrinhs, "ID", "Title");
            return View();
        }

        //
        // POST: /Comment/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comment comment,int loai,int iddietvr,int idlaptrinh)
        {
            if (ModelState.IsValid)
            {
                comment.Loai = loai;
                comment.DietVRID = iddietvr;
                comment.LapTrinhID = idlaptrinh;
                comment.DateCreated = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                //return RedirectToAction("Index");
                return PartialView("viewComment", comment);
            }

            ViewBag.DietVRID = new SelectList(db.DietVRs, "ID", "Title", comment.DietVRID);
            ViewBag.LapTrinhID = new SelectList(db.Laptrinhs, "ID", "Title", comment.LapTrinhID);
            return View(comment);
        }

        //
        // GET: /Comment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.DietVRID = new SelectList(db.DietVRs, "ID", "Title", comment.DietVRID);
            ViewBag.LapTrinhID = new SelectList(db.Laptrinhs, "ID", "Title", comment.LapTrinhID);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DietVRID = new SelectList(db.DietVRs, "ID", "Title", comment.DietVRID);
            ViewBag.LapTrinhID = new SelectList(db.Laptrinhs, "ID", "Title", comment.LapTrinhID);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Project/Project/Controllers/DietVRController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    [Authorize]
    public class DietVRController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /DietVR/
        [AllowAnonymous]
        public ActionResult Index(string Publishers, string strSearch)
        {
            var dietvr = db.DietVRs.Include(p => p.UserProfile);
            //return View(posts.ToList());
            //Select all Book records
            var dietvirus = from b in db.DietVRs

                          select b;

            //Get list of Book publisher
            var publisherList = from c in dietvirus
                                orderby c.Title
                                select c.Title;

            //Set distinct list of publishers in ViewBag property
            //ViewBag.Publishers = new SelectList(publisherList.Distinct());

            //Search records by Book Name 
            if (!string.IsNullOrEmpty(strSearch))
                dietvirus = dietvirus.Where(m => m.Title.Contains(strSearch));
            return View(dietvirus);
            //return View(db.DiaDanhs.ToList());
        }

        //
        // GET: /DietVR/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            DietVR dietvr = db.DietVRs.Find(id);
            if (dietvr == null)
            {
                return HttpNotFound();
            }
            ViewData["idlaptrinh"] = 1;
            ViewData["iddietvr"] = id;
            ViewData["Loai"] = 1;
            return View(dietvr);
        }

        //
        // GET: /DietVR/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /DietVR/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DietVR dietvr, string Content)
        {
            if (ModelState.IsValid)
            {
                dietvr.DateCreate = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).Where(y => y.UserName == User.Identity.Name).Single().UserId;
                dietvr.UserProfileID = userid;
                //Tao list các tag
                List<Tag> Tags = new List<Tag>();
                //tach cac Tag theo dau ,
                string[] TagContent = Content.Split(',');
                //Lập các tag vừa tách
                foreach (string item in TagContent)
                {
                    //Tìm xem tag content đã có hay chưa
                    Tag TagExists = null;
                    var ListTag = db.Tags.Where(y => y.Content.Equals(item.Trim()));
                    if (ListTag.Count() > 0)
                    {
                        //nếu có tag rồi thì add thêm Post vào
                        TagExists = ListTag.First();
                        TagExists.DietVRs.Add(dietvr);
                    }
                    else
                    {
                        //nếu chưa có tag thì tạo mới
                        TagExists = new Tag();
                        TagExists.Content = item.Trim();
                        TagExists.DietVRs = new List<DietVR>();
                        TagExists.DietVRs.Add(dietvr);
                    }
                    //add vào List các tag
                    Tags.Add(TagExists);
                }
                //Gán List Tag cho Post
                dietvr.Tags = Tags;
                db.DietVRs.Add(dietvr);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dietvr);
        }

        //
        // GET: /DietVR/Edit/5

        public ActionResult Edit(int id = 0)
        {
            DietVR dietvr = db.DietVRs.Find(id);
            if (dietvr == null)
            {
                return HttpNotFound();
            }
            return View(dietvr);
        }

        //
        // POST: /DietVR/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DietVR dietvr)
        {
            if (ModelState.IsValid)
            {
                dietvr.DateCreate = DateTime.Now;
                db.Entry(dietvr).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dietvr);
        }

        //
        // GET: /DietVR/Delete/5

        public ActionResult Delete(int id = 0)
        {
            DietVR dietvr = db.DietVRs.Find(id);
            if (dietvr == null)
            {
                return HttpNotFound();
            }
            return View(dietvr);
        }

        //
        // POST: /DietVR/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DietVR dietvr = db.DietVRs.Find(id);
            db.DietVRs.Remove(dietvr);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Project/Project/Controllers/RatingVRController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class RatingVRController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /RatingVR/

        public ActionResult Index()
        {
            var ratingvrs = db.RatingVRs.Include(r => r.DietVRs);
            return View(ratingvrs.ToList());
        }

        //
        // GET: /RatingVR/Details/5

        public ActionResult Details(int id = 0)
        {
            RatingVR ratingvr = db.RatingVRs.Find(id);
            if (ratingvr == null)
            {
                return HttpNotFound();
            }
            return View(ratingvr);
        }

        //
        // GET: /RatingVR/Create

        public ActionResult Create()
        {
            ViewBag.DietVRID = new SelectList(db.DietVRs, "ID", "Title");
            return View();
        }

        //
        // POST: /RatingVR/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RatingVR ratingvr,int iddietvr)
        {
            if (ModelState.IsValid)
            {
                ratingvr.DietVRID = iddietvr;
                db.RatingVRs.Add(ratingvr);
                db.SaveChanges();
                return RedirectToAction("Details/" + iddietvr, "DietVR");
            }

            ViewBag.DietVRID = new SelectList(db.DietVRs, "ID", "Title", ratingvr.DietVRID);
            return View(ratingvr);
        }

        //
        // GET: /RatingVR/Edit/5

        public ActionResult Edit(int id = 0)
        {
            RatingVR ratingvr = db.RatingVRs.Find(id);
            if (ratingvr == null)
            {
                return HttpNotFound();
            }
            ViewBag.DietVRID = new SelectList(db.DietVRs, "ID", "Title", ratingvr.DietVRID);
            return View(ratingvr);
        }

        //
        // POST: /RatingVR/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RatingVR ratingvr)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ratingvr).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DietVRID = new SelectList(db.DietVRs, "ID", "Title", ratingvr.DietVRID);
            return View(ratingvr);
        }

        //
        // GET: /RatingVR/Delete/5

        public ActionResult Delete(int id = 0)
        {
            RatingVR ratingvr = db.RatingVRs.Find(id);
            if (ratingvr == null)
            {
                return HttpNotFound();
            }
            return View(ratingvr);
        }

        //
        // POST: /RatingVR/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RatingVR ratingvr = db.RatingVRs.Find(id);
            db.RatingVRs.Remove(ratingvr);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Project/Project/Views/DietVR/Create.cshtml
@model Project.Models.DietVR

@{
    ViewBag.Title = "Softvn.com - Nơi chia sẻ phần mềm và thủ thuật";
}

<h2>Phần Mềm Diệt Virus</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>DietVR</legend>

        <div class="editor-label">
           <h3>Tiêu Đề</h3>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            <h3>Nội Dung</h3>
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>
        <div class="editor-label">
            <h3>Tag</h3> <i>(Thêm các mô tả cho bài viết)</i>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => new Project.Models.Tag().Content)
            @Html.ValidationMessageFor(model => new Project.Models.Tag().Content)
        </div>
        <p>
            <input type="submit" value="Đăng Bài" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/Project/Views/DietVR/Delete.cshtml
@model Project.Models.DietVR

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>DietVR</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfileID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfileID)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Project/Project/Views/DietVR/Details.cshtml
@model Project.Models.DietVR

@{
    ViewBag.Title = "Softvn.com - Nơi chia sẻ phần mềm và thủ thuật";
}

<h2>Phần Mềm Diệt Virus</h2>

<fieldset>
    <legend>DietVR</legend>

    <div class="display-field">
        <h4>@Html.DisplayFor(model => model.Title)</h4>
    </div>
    @foreach (var rate in Model.RatingVRs.OrderByDescending(x => x.Diem).Take(1))
    {
        <div class="display-field">
            <i>Đánh giá: @Html.DisplayFor(model => rate.Diem)</i>
        </div>
    }
    Đăng ngày: @Html.DisplayFor(model => model.DateCreate) bởi @Html.DisplayFor(model => model.UserProfile.UserName)
    <div class="display-label">
        <h3>Nội Dung</h3>
    </div>

        <div class="display-field">
            @Html.DisplayFor(model => model.Body)
        </div>

        
</fieldset>

<fieldset>
    <legend>Tag</legend>
    <div class="display-label">
        <h3>Tag:</h3>
    </div>
    @foreach (var tag in Model.Tags)
    {
        <div class="display-field">
            <i> @Html.ActionLink(tag.Content.ToString(), "Details", new { Controller = "Tag", action = "Details", id = tag.ID })</i>
        </div>
    }
</fieldset>
@Html.Partial("_addRatingVR", new Project.Models.RatingVR(), ViewData)
@Html.Partial("_addComment", new Project.Models.Comment(), ViewData)
<fieldset>
    <legend>Comment</legend>
    <div class="display-field">
        <h3>Comment:</h3>
    </div>
    <div id="result">
        @foreach (var comment in Model.Comments.OrderByDescending(x => x.DateCreated).Take(10))
        {
            if (comment.Loai == 1)
            {
                <div class="display-field">
                    <h5>Tác giả: @Html.DisplayFor(x => comment.Author)</h5>
                </div>
                <div class="display-field">
                    Cách đây: @Html.DisplayFor(x => comment.LastTime) phút
                </div>
                <div class="display-field">
                    @Html.DisplayFor(x => comment.Body)
                </div>
            }
        }
    </div>
</fieldset>

<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project/Project/Views/DietVR/Edit.cshtml
@model Project.Models.DietVR

@{
    ViewBag.Title = "Softvn.com - Nơi chia sẻ phần mềm và thủ thuật";
}


<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>DietVR</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/Project/Views/DietVR/Index.cshtml
@model IEnumerable<Project.Models.DietVR>

@{
    ViewBag.Title = "Softvn.com - Nơi chia sẻ phần mềm và thủ thuật hữu ích";
}
@using (Html.BeginForm("Index", "DietVR", FormMethod.Get))
{
    <p>
        @*Publisher: @Html.DropDownList("Publishers", "All")*@
        Tên bài viết: @Html.TextBox("strSearch")
        <input type="submit" value="Search" />
    </p>
} 

<p>
    @Html.ActionLink("Đăng Bài Mới", "Create")
</p>
<style>
    table, th, td {
        border: 2px solid #ff0000;
        border-collapse: collapse;
    }
</style>
<table>
    <tr>
        <th width="192">Tiêu đề</th>
        <th width="750">Nội dung</th>
        <th width="130">Ngày đăng</th>
        <th width="140">Thao tác</th>

    </tr>
    @foreach (var item in Model.OrderByDescending(x => x.DateCreate))
    {
        <tr>
            <td>@Html.ActionLink(item.Title, "Details", new { id = item.ID })</td>
            <td>@item.Body</td>
            <td>@item.DateCreate</td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.ID })
                @Html.ActionLink("Chi tiết", "Details", new { id = item.ID })
                @Html.ActionLink("Xóa", "Delete", new { id = item.ID })
            </td>

        </tr>
    }

</table>

Project/Project/Views/DietVR/_addComment.cshtml
@model Project.Models.Comment


@using (Html.BeginForm("Create", "Comment", FormMethod.Post, new { id = "My-Form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Comment</legend>
        <div class="display-label">
            <h4>Bình Luận</h4>
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Author)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Author)
            @Html.ValidationMessageFor(model => model.Author)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <div>
            @Html.Hidden("iddietvr", ViewData["iddietvr"])
            @Html.Hidden("idlaptrinh", ViewData["idlaptrinh"])
            @Html.Hidden("Loai", ViewData["Loai"])
            <p>
                <input type="submit" value="Bình luận" />
            </p>
        </div>
    </fieldset>
}

<script src="~/Scripts/addComment.js"></script>

Project/Project/Views/DietVR/_addRatingVR.cshtml
@model Project.Models.RatingVR


@using (Html.BeginForm("Create", "RatingVR", new { iddietvr = ViewData["iddietvr"] }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Rating</legend>

        <div class="editor-label">
            <h4>Đánh Giá</h4>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Diem)
            @Html.ValidationMessageFor(model => model.Diem)
        </div>

        <p>
            <input type="submit" value="Đánh giá" />
        </p>
    </fieldset>
}