Project/Project/Models/LapTrinh.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project.Models
{
    public class LapTrinh
    {
        public int ID { set; get; }
        [Required(ErrorMessage = "Dữ liệu chưa được nhập")]
        [StringLength(500, ErrorMessage = "Số lượng ký tự từ 20-500", MinimumLength = 2)]
        public String Title { set; get; }

        [Required(ErrorMessage = "Dữ liệu chưa được nhập")]
        [StringLength(5000, ErrorMessage = "Số lượng ký tự từ 20-5000", MinimumLength = 2)]
        public String Body { set; get; }

        [Required(ErrorMessage = "Dữ liệu chưa được nhập")]

        [DataType(DataType.DateTime)]
        public DateTime DateCreate { set; get; }

        //1 bài viết của 1 người dùng
        public virtual UserProfile UserProfile { set; get; }
        public int UserProfileID { set; get; }
        // 1 bài viết có nhiều Comment
        public virtual ICollection<Comment> Comments { set; get; }
        public virtual ICollection<RatingLT> RatingLTs { set; get; }
    }
}

Project/Project/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class CommentController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Comment/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.DietVRs).Include(c => c.LapTrinhs);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create

        public ActionResult Create()
        {
            ViewBag.DietVRID = new SelectList(db.DietVRs, "ID", "Title");
            ViewBag.LapTrinhID = new SelectList(db.Laptrinhs, "ID", "Title");
            return View();
        }

        //
        // POST: /Comment/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comment comment,int loai,int iddietvr,int idlaptrinh)
        {
            if (ModelState.IsValid)
            {
                comment.Loai = loai;
                comment.DietVRID = iddietvr;
                comment.LapTrinhID = idlaptrinh;
                comment.DateCreated = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                //return RedirectToAction("Index");
                return PartialView("viewComment", comment);
            }

            ViewBag.DietVRID = new SelectList(db.DietVRs, "ID", "Title", comment.DietVRID);
            ViewBag.LapTrinhID = new SelectList(db.Laptrinhs, "ID", "Title", comment.LapTrinhID);
            return View(comment);
        }

        //
        // GET: /Comment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.DietVRID = new SelectList(db.DietVRs, "ID", "Title", comment.DietVRID);
            ViewBag.LapTrinhID = new SelectList(db.Laptrinhs, "ID", "Title", comment.LapTrinhID);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DietVRID = new SelectList(db.DietVRs, "ID", "Title", comment.DietVRID);
            ViewBag.LapTrinhID = new SelectList(db.Laptrinhs, "ID", "Title", comment.LapTrinhID);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Project/Project/Controllers/LapTrinhController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    [Authorize]
    public class LapTrinhController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /LapTrinh/
        [AllowAnonymous]
        public ActionResult Index(string Publishers, string strSearch)
        {
            var laptrinht = db.Laptrinhs.Include(p => p.UserProfile);
            //return View(posts.ToList());
            //Select all Book records
            var laptrinhs = from b in db.Laptrinhs

                            select b;

            //Get list of Book publisher
            var publisherList = from c in laptrinhs
                                orderby c.Title
                                select c.Title;

            //Set distinct list of publishers in ViewBag property
            //ViewBag.Publishers = new SelectList(publisherList.Distinct());

            //Search records by Book Name 
            if (!string.IsNullOrEmpty(strSearch))
                laptrinhs = laptrinhs.Where(m => m.Title.Contains(strSearch));
            return View(laptrinhs);
            //return View(db.DiaDanhs.ToList());
        }

        //
        // GET: /LapTrinh/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            LapTrinh laptrinh = db.Laptrinhs.Find(id);
            if (laptrinh == null)
            {
                return HttpNotFound();
            }
            ViewData["iddietvr"] = 1;
            ViewData["idlaptrinh"] = id;
            ViewData["Loai"] = 2;
            return View(laptrinh);
        }

        //
        // GET: /LapTrinh/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /LapTrinh/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LapTrinh laptrinh)
        {
            if (ModelState.IsValid)
            {
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).Where(y => y.UserName == User.Identity.Name).Single().UserId;
                laptrinh.UserProfileID = userid;
                laptrinh.DateCreate = DateTime.Now;
                db.Laptrinhs.Add(laptrinh);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(laptrinh);
        }

        //
        // GET: /LapTrinh/Edit/5

        public ActionResult Edit(int id = 0)
        {
            LapTrinh laptrinh = db.Laptrinhs.Find(id);
            if (laptrinh == null)
            {
                return HttpNotFound();
            }
            return View(laptrinh);
        }

        //
        // POST: /LapTrinh/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LapTrinh laptrinh)
        {
            if (ModelState.IsValid)
            {
                laptrinh.DateCreate = DateTime.Now;
                db.Entry(laptrinh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(laptrinh);
        }

        //
        // GET: /LapTrinh/Delete/5

        public ActionResult Delete(int id = 0)
        {
            LapTrinh laptrinh = db.Laptrinhs.Find(id);
            if (laptrinh == null)
            {
                return HttpNotFound();
            }
            return View(laptrinh);
        }

        //
        // POST: /LapTrinh/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LapTrinh laptrinh = db.Laptrinhs.Find(id);
            db.Laptrinhs.Remove(laptrinh);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Project/Project/Controllers/RatingLTController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class RatingLTController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /RatingLT/

        public ActionResult Index()
        {
            var ratinglts = db.RatingLTs.Include(r => r.LapTrinhs);
            return View(ratinglts.ToList());
        }

        //
        // GET: /RatingLT/Details/5

        public ActionResult Details(int id = 0)
        {
            RatingLT ratinglt = db.RatingLTs.Find(id);
            if (ratinglt == null)
            {
                return HttpNotFound();
            }
            return View(ratinglt);
        }

        //
        // GET: /RatingLT/Create

        public ActionResult Create()
        {
            ViewBag.LapTrinhID = new SelectList(db.Laptrinhs, "ID", "Title");
            return View();
        }

        //
        // POST: /RatingLT/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RatingLT ratinglt,int idlaptrinh)
        {
            if (ModelState.IsValid)
            {
                ratinglt.LapTrinhID = idlaptrinh;
                db.RatingLTs.Add(ratinglt);
                db.SaveChanges();
                return RedirectToAction("Details/" + idlaptrinh, "LapTrinh");
            }

            ViewBag.LapTrinhID = new SelectList(db.Laptrinhs, "ID", "Title", ratinglt.LapTrinhID);
            return View(ratinglt);
        }

        //
        // GET: /RatingLT/Edit/5

        public ActionResult Edit(int id = 0)
        {
            RatingLT ratinglt = db.RatingLTs.Find(id);
            if (ratinglt == null)
            {
                return HttpNotFound();
            }
            ViewBag.LapTrinhID = new SelectList(db.Laptrinhs, "ID", "Title", ratinglt.LapTrinhID);
            return View(ratinglt);
        }

        //
        // POST: /RatingLT/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RatingLT ratinglt)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ratinglt).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LapTrinhID = new SelectList(db.Laptrinhs, "ID", "Title", ratinglt.LapTrinhID);
            return View(ratinglt);
        }

        //
        // GET: /RatingLT/Delete/5

        public ActionResult Delete(int id = 0)
        {
            RatingLT ratinglt = db.RatingLTs.Find(id);
            if (ratinglt == null)
            {
                return HttpNotFound();
            }
            return View(ratinglt);
        }

        //
        // POST: /RatingLT/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RatingLT ratinglt = db.RatingLTs.Find(id);
            db.RatingLTs.Remove(ratinglt);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Project/Project/Views/LapTrinh/Create.cshtml
@model Project.Models.LapTrinh

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>LapTrinh</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/Project/Views/LapTrinh/Delete.cshtml
@model Project.Models.LapTrinh

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>LapTrinh</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfileID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfileID)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Project/Project/Views/LapTrinh/Details.cshtml
@model Project.Models.LapTrinh

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>LapTrinh</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>
    @foreach (var rate in Model.RatingLTs.OrderByDescending(x => x.Diem).Take(1))
    {
        <div class="display-field">
            <i>Đánh giá: @Html.DisplayFor(model => rate.Diem)</i>
        </div>
    }
    Đăng ngày: @Html.DisplayFor(model => model.DateCreate) bởi @Html.DisplayFor(model => model.UserProfile.UserName)
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

</fieldset>


@Html.Partial("_addRatingLT", new Project.Models.RatingLT(), ViewData)
@Html.Partial("_addCommentLT", new Project.Models.Comment(), ViewData)
<fieldset>
    <legend>Comment</legend>
    <div class="display-field">
        <h3>Comment:</h3>
    </div>
    <div id="result">
        @foreach (var comment in Model.Comments.OrderByDescending(x => x.DateCreated).Take(10))
        {
            if (comment.Loai == 2)
            {
                <div class="display-field">
                    <h5>Tác giả: @Html.DisplayFor(x => comment.Author)</h5>
                </div>
                <div class="display-field">
                    Cách đây: @Html.DisplayFor(x => comment.LastTime) phút
                </div>
                <div class="display-field">
                    @Html.DisplayFor(x => comment.Body)
                </div>
            }

        }
    </div>
</fieldset>


<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project/Project/Views/LapTrinh/Edit.cshtml
@model Project.Models.LapTrinh

@{
    ViewBag.Title = "Softvn.com - Nơi chia sẻ phần mềm và thủ thuật";
}

}

<h2>Phần Mềm Lập Trình</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>LapTrinh</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/Project/Views/LapTrinh/Index.cshtml
@model IEnumerable<Project.Models.LapTrinh>

@{
    ViewBag.Title = "Softvn.com - Nơi chia sẻ phần mềm và thủ thuật hữu ích";
}
@using (Html.BeginForm("Index", "LapTrinh", FormMethod.Get))
{
    <p>
        @*Publisher: @Html.DropDownList("Publishers", "All")*@
        Tên bài viết: @Html.TextBox("strSearch")
        <input type="submit" value="Search" />
    </p>
}

<p>
    @Html.ActionLink("Đăng Bài Mới", "Create")
</p>
<style>
    table, th, td {
        border: 2px solid #ff0000;
        border-collapse: collapse;
    }
</style>
<table>
    <tr>
        <th width="192">Tiêu đề</th>
        <th width="750">Nội dung</th>
        <th width="130">Ngày đăng</th>
        <th width="140">Thao tác</th>

    </tr>
    @foreach (var item in Model.OrderByDescending(x => x.DateCreate))
    {
        <tr>
            <td>@Html.ActionLink(item.Title, "Details", new { id = item.ID })</td>
            <td>@item.Body</td>
            <td>@item.DateCreate</td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.ID })
                @Html.ActionLink("Chi tiết", "Details", new { id = item.ID })
                @Html.ActionLink("Xóa", "Delete", new { id = item.ID })
            </td>

        </tr>
    }

</table>

Project/Project/Views/LapTrinh/_addCommentLT.cshtml
@model Project.Models.Comment

@using (Html.BeginForm("Create", "Comment", FormMethod.Post, new { id = "My-Form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Comment</legend>
        <div class="display-label">
            <h4>Bình Luận</h4>
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Author)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Author)
            @Html.ValidationMessageFor(model => model.Author)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <div>
            @Html.Hidden("iddietvr", ViewData["iddietvr"])
            @Html.Hidden("idlaptrinh", ViewData["idlaptrinh"])
            @Html.Hidden("Loai", ViewData["Loai"])
            <p>
                <input type="submit" value="Bình luận" />
            </p>
        </div>
    </fieldset>
}
<script src="~/Scripts/addComment.js"></script>

Project/Project/Views/LapTrinh/_addRatingLT.cshtml
@model Project.Models.RatingLT

@using (Html.BeginForm("Create", "RatingLT", new { idlaptrinh = ViewData["idlaptrinh"] }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Rating</legend>

        <div class="editor-label">
            <h4>Đánh Giá</h4>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Diem)
            @Html.ValidationMessageFor(model => model.Diem)
        </div>

        <p>
            <input type="submit" value="Đánh giá" />
        </p>
    </fieldset>
}